#!/bin/bash

set -e -x

# stow is relative to this directory
cd $(dirname $0)

# global assumptions
mkdir -p ~/bin ~/.config

NEOVIM_CONFIG='https://github.com/youssb/dot-nvim.git'

GIT_DUET_RELEASE='https://github.com/git-duet/git-duet/releases/download/0.6.0/darwin_amd64.tar.gz'

function gimme() {
  local name=$(basename $1)
  if brew list | grep "\\<$name\\>"; then
    brew outdated "$name" || brew upgrade "$@"
  else
    brew install "$@"
  fi
}

function gimme_all() {
  for x in "$@"; do
    gimme "$x"
  done
}

function gimme_cask() {
  for x in "$@"; do
    if ! brew list --cask | grep "\\<$x\\>"; then
      brew install --cask "$x"
    fi
  done
}

# install homebrew
if ! which brew >/dev/null; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

export ZSH_DISABLE_COMPFIX=true
export RUNZSH=no
rm -rf ~/.oh-my-zsh
# install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"


cp -rf .zshrc ~/.zshrc
# chsh -s $(which zsh)

# install cask
brew tap homebrew/cask
gimme cask

# install simple config manager
gimme stow

# install neovim as ~/bin/vim, + python support
gimme_all neovim/neovim/neovim python
pip3 install neovim
nvim --headless +UpdateRemotePlugins +qa
ln -sf "$(which nvim)" ~/bin/vim

# bootstrap neovim config (`git pull` on your own)
if ! [ -e ~/.config/nvim ]; then
  git clone "$NEOVIM_CONFIG" ~/.config/nvim --recursive
fi

# install git + git config + sane git duet
gimme git
stow git
curl -L "$GIT_DUET_RELEASE" | tar -C ~/bin -zxf -

#install zsh-plugins
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# install golang toolchain
gimme go
nvim --headless +GoInstallBinaries +qa

# install postgres
gimme postgresql
ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents

# install gui livelihood
if ! [ -e "/Applications/Google Chrome.app" ]; then
  gimme_cask google-chrome
fi

if ! [ -e /Applications/iTerm.app ]; then
  gimme_cask iterm2
fi

if ! [ -e /Applications/firefox.app ]; then
  gimme_cask firefox
fi

if ! [ -e /Applications/Microsoft Outlook.app ]; then
  gimme_cask microsoft-outlook
fi

if ! [ -e /Applications/Spotify.app ]; then
  gimme_cask spotify
fi

if ! [ -e /Applications/onedrive.app ]; then
  gimme_cask onedrive
fi

gimme_cask rectangle


# install cli livelihood
gimme_all jq yq htop stress direnv the_silver_searcher lastpass-cli jump autojump watch hub

# install frontent stuff
gimme_all node elm yarn
npm install -g npm
npm install -g elm-test
npm install -g elm-format
npm install -g @angular/cli

if ! [ -e /Applications/Docker.app ]; then
  gimme_cask docker
fi

gimme_all helm
gimme_cask google-cloud-sdk

/bin/zsh  -c 'source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
/bin/zsh -c 'source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'

gcloud init

gimme heroku/brew/heroku

brew tap teamookla/speedtest
gimme speedtest

# install rload: a simple script to load github private key from lastpass
install ./rload ~/bin/rload

