#!/bin/bash

rload() {
 KEY=$(mktemp /tmp/secret.XXXXXX)
 HOURS=$1
 chmod 600 $KEY
 lpass show github-key --field="Private Key" > $KEY
 if [ -z $HOURS ]; then
   /usr/bin/ssh-add -D
   /usr/bin/ssh-add $KEY
 else
   /usr/bin/ssh-add -D
   /usr/bin/ssh-add -t ${HOURS}H $KEY
 fi
 rm "$KEY"
}

rload
